micronaut:
  application:
    name: apiAluraFlix
  server:
    port: 5000
  data:
    pageable:
      default-page-size: 10
      max-page-size: 50
      sort-ignore-case: true
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

datasources:
  default:
    url: jdbc:h2:mem:aluraflix_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa.default.properties.hibernate:
  hbm2ddl.auto: none
  show_sql: true

flyway:
  datasources:
    default:
      enabled: true

endpoints:
  all.path: /actuator
  beans:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
  flyway:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  prometheus:
    sensitive: false