DROP TABLE IF EXISTS video;

CREATE TABLE video (
    `id` BIGINT GENERATED BY DEFAULT AS IDENTITY,
    `titulo` VARCHAR(100) NOT NULL,
    `descricao` VARCHAR(255) NOT NULL,
    `url` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
);

INSERT INTO
    video (`titulo`, `descricao`, `url`)
VALUES
    (
        'My Pet Seagull Day 75',
        'Watching the Sunset with My Pet Seagull & Tasty Snackos',
        'https://www.youtube.com/watch?v=RoyDgTp2mac&ab_channel=FeedingSteven'
    );