DROP TABLE IF EXISTS categoria;

CREATE TABLE categoria (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "titulo" VARCHAR(100) NOT NULL,
    "cor" VARCHAR(7) NOT NULL,
    PRIMARY KEY ("id")
);

INSERT INTO
    categoria ("titulo", "cor")
VALUES
    (
        'Livre',
        '#B0B0B0'
    );

ALTER TABLE video
ADD "categoria_id" BIGINT;

ALTER TABLE video
ADD CONSTRAINT FK_categoria_id
FOREIGN KEY (categoria_id) REFERENCES categoria(id);

UPDATE video
SET categoria_id = 1;